### PR TITLE
Haxe4: OpIn

### PR DESCRIPTION
**Pull request by AxGord**

### CODE REVIEW

**Comment by Atry** [comment]
It seems that the CI configuration have to be updated for Haxe 4

**Comment by Atry** [comment]
@AxGord Since I am not actively using Haxe recently. I wonder if you can maintain a new Haxe 4 branch of this library. I can grant the maintainer permission of this repository to you.

**Comment by AxGord** [comment]
@Atry Yes, I can maintain Haxe 4 branch.

**Comment by Atry** [comment]
@AxGord Could you please adjust the CI configuration for Haxe 4 before merging?

**Comment by Atry** [comment]
@AxGord I created an organization for this project.

**Pull request merged**
